[build]
  publish = "dist"

[[redirects]]
  from = "/webhook/*"
  to = "https://n8n.simplifies.click/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/video-proxy/*"
  to = "https://nyc3.digitaloceanspaces.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/media-proxy/*"
  to = "https://media-catalog.nyc3.digitaloceanspaces.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/generations-proxy/*"
  to = "https://video-generations.nyc3.digitaloceanspaces.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/webhook/*"
  [headers.values]
    Access-Control-Allow-Args = "*"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS"

[[headers]]
  for = "/video-proxy/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/media-proxy/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/generations-proxy/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
